### PR TITLE
Improved Schematic & PDF readability

### PR DESCRIPTION
**Pull request by Paul-Ver**
Improved on a few comments in
https://www.youtube.com/watch?v=2Z3URu9vQBk&t=1s

### CODE REVIEW

**Comment by drandyhaas** [comment]
Hi,
Thanks for the help! However, when I try loading your improved .sch in eagle and then run an ERC it gives the following errors and warnings... 

clipboard02

**Comment by Paul-Ver** [comment]
Ah, actually, you're completely right.
I thought eagle would automatically connect wires running to the same point when overlapping, but that was incorrect.

I'll have to take a look at fixing those issues

**Comment by drandyhaas** [comment]
I'm almost done with my fixed version...
Maybe wait for that.

**Comment by drandyhaas** [comment]
And done!

**Pull request closed without merging**
