### PR TITLE
Initial check-in of Dockerfile to run Haasoscope in a container.

### PR DESCRIPTION
**Pull request by Thirsty2**
This Dockerfile allows you to run the Haasoscope software in a container.  Instructions are in the comments at the bottom of the dockerfile.  Currently, the only Dockerfile runs the python3 version of Haasoscope.  It should be possible to create a python2 version if needed.

### CODE REVIEW

**Comment by drandyhaas** [comment]
Neat, thanks.
I have never used docker, but I know of it. 
Can you please add a Readme.txt that explains how to use this on windows / Mac / Linux? Then I will test it, and then accept the pull.

**Comment by Thirsty2** [comment]
You are welcome.  Thanks for the cool scope!  I will write up a readme.txt but I can only test it on Linux at the moment.  I may be able to test it on Windows 10 with WSL2 in a couple of days if I can still get my old laptop to boot that.  I don’t have access to a Mac.  I tried it on a chromebook running Linux Beta in a Crostini container but I can’t get it to see the scope as a USB device yet.

My Linux laptop has a 4k display and the scaling of the controls is off.  I suspect there’s an easy fix but I haven’t found it yet.  I just got the scope today.

Doug

**Comment by Thirsty2** [comment]
I added a README-Docker.md file, which gives some background on Docker, and a link to the Docker website where installation instructions, tutorials, etc. may be found.  There are instructions in the README for building and running the container under Linux.  The instructions for Win 10 with Docker running under the Microsoft Linux Kernel in WSL2 should be nearly identical, and I expect the instructions under Mac should also be very similar.  There may be some differences in what is required to display the GUI.  Since the container is running Linux, it expects to see an X display, which is provided as a $DISPLAY environment var on the command line, along with a volume mapped .X11-unix dir.

**Comment by Thirsty2** [comment]
It appears that Win 10 WSL2 does not allow the Linux kernel running under WSL2 to get access to most USB devices.  I have not been able to get the Haasoscope to show up at all in WSL2.  Until this is allowed, Docker under WSL2 won't have access to the hardware.  It may be possible to get a regular Windows Docker installation to work (not using WSL2) but I installed Docker under WSL2 per the recommendations.  I don't have another Windows system to try a native Windows Docker Desktop install.

**Comment by drandyhaas** [comment]
I tried it on an Ubuntu 20.04 virtual machine, but had some problems:
<pre>
osboxes@osboxes:~/Downloads/Haasoscope/dockerfiles$ xhost +local:docker
[sudo] password for osboxes: 
non-network local connections being added to access control list
osboxes@osboxes:~/Downloads/Haasoscope/dockerfiles$ docker run --privileged -it --rm -e DISPLAY=$DISPLAY -v "/tmp/.X11-unix:/tmp/.X11-unix" haasoscope bash
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
osboxes@osboxes:~/Downloads/Haasoscope/dockerfiles$ sudo docker run --privileged -it --rm -e DISPLAY=$DISPLAY -v "/tmp/.X11-unix:/tmp/.X11-unix" haasoscope bash
root@8cc2cb246d53:~/Haasoscope/software# python3 HaasoscopeQt.py
Loading HaasoscopeLibQt.py
posix.uname_result(sysname='Linux', nodename='8cc2cb246d53', release='5.4.0-48-generic', version='#52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020', machine='x86_64')
num main ADC and max10adc bytes for all boards =  2048 and 0
Construction done
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
root@8cc2cb246d53:~/Haasoscope/software# 
</pre>

**Comment by drandyhaas** [comment]
Ah, I need to add "--net=host" to the docker run command, then it works.

**Pull request merged**
