### PR TITLE
3D printable case

### PR DESCRIPTION
**Pull request by danielkucera**
I've created a 3D model for bottom case. It might come handy also for others.

### CODE REVIEW

**Comment by drandyhaas** [comment]
Thanks!

**Comment by luftek** [comment]
Thank you!

**Comment by drandyhaas** [comment]
Note that I imoroved the case design a bit, and also made a version for Haasoscope v9. Links are in the readme file.

**Comment by luftek** [comment]
Thank you. I see you added holes and some support material.
I like that you have added .stl to repository. Github visualizes .stl great. https://github.com/drandyhaas/Haasoscope/tree/master/3d

Don't like the links. For downloading they require Autodesk login information/sign up.

**Pull request merged**
